# Generated by Django 3.2.4 on 2021-07-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls_save',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
